language: r
dist: trusty
cache: packages
env:
  global:
    secure: CUPgVYvOIDikOCsuvQxboibAH9nsxiRwqiEhMPMvutmxD5zae7eXTfRL5UYjRUs6lj5QUrMzW3MsXrci9j84ZelBy6zY/BJ4azEV5i4NKNeZ72i/NcJ3yDWnGL16JLaT2ACPCbE22vn/XLokVv5W9JMIs0uiPiiNyxGQWW8kprQ9/rJyGbEZRm4pfi3aeSH1hmn7MG3XEmHJpj54RoRcX2oaCtMb3kAIlnnDf4Z31cVrgdAqqrPONtlWF3KnH/DlukY/t2nmMGbvVyemMfF0k50vpEuOw9XhiDNoKzdSvRkn/CQRewW26PbStLB+svlNpTYPffVErKbSiMMlPJoZiqbROlQdjJEI7C/50x28d4xuqmy3YCqMLeEEIKYUY9bREoksM5YwyAxSXZkmKFKj8undPe4/jWgYrsR/DjwrOqdM1QQs0ouLNqX+9643v51u6wHMoHk62NdOxr1TBvzphaWl1oabJHM9ZDx50AlszShlZQLys/kthpQPErlxlvtPUI+Mw5NlBz3fYwrdU/y/ySzp3xLZjBu2wy8O/wLCx2brC2vUVEgt3ZMkyLwdTUbqsnjL+xfKA2pLnDK2+Ykxp8MuNZklxX5dnZudDP7xHbpuS9r0rrCBFTmyzDM2Hzc1s0RlpJeeiorQlmO9Zyzr/qmNNqV7uUiQVwmwjCy2xP0=
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: public
  keep-history: true
  on:
    branch: feature/integrate-travis
