language: r
dist: trusty
cache: packages
env:
  global:
    secure: NC8E0zAtz7ew59qkqW3BoQrkOD9cTMrz1Ry044DYtKG6eJzPv3fREUaTqk4Wcukc9Nf6tagt9k9a1lGjzSJQenRHAxk2H42UFytkpMgSI48niOgrVWOsgh9r706ahbhwK9W6ndxI2k2N2slW4D79597NmI5qJh+MlPSfsnRot7ym+I3KNSNLiS9l/G0nKMWNswBNTbhWfFPG216LGRVJ3lj91b1DWOJOBt0hDosEH0eckEAAbU8/fiCbhgawcmRbPVJB8Ax6QB10SA0qNiH75FMnAS3HH9tnoYzVxXDwp+eXbgIMQq0K1G6nkI1RXgPHzbHrWloQxLVjOe78nTW8AYcT5r0GFEP+do5u054jXTZ8ZNJB+Wwzgw2vuvj7dxl2SXiz649hLywZJHSuce1BYcZ0Fdup1U20kuy3L2lnxruD9w6WdbvaGIxkJ4KZUx3p+w5rzYdWhbPFapom0/ZnCiEu3DOPPy5MGd59rT+yo/zrnZZDDE8RNUFHgSVNSi/t8dENF3fvToRMsPtEJrVg+soiz72E+DdZAqMTsNspOrVHHQ+yJE8UUdIFsU/GakekF5ZYN3z7bUYdbxw7cdljBDynohUSE4HqUBZDSBfbzwLCooJI+aRP/d8SW0eMuZz9IvyFeBNzg5xyu/oSkvyBL2/4NM5MOTtBHF2tCIApO18=
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
- touch public/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: public
  keep-history: true
  on:
    branch: feature/integrate-travis
