---
# heading of document
title: 记忆扫描（MemoryScan） # Chinese name（English name）
author: 张亮
date: 2018-11-15 # format 2006-01-01
# slug
slug: 00302-memoryscan # code-English name
# specific parameters for current task
code: '00302'
sdk: 301
# hugo taxonomy related
tasknames: "短时记忆"
categories:
- 文档
- C2框架
# blogdown output
output:
  blogdown::html_page:
    toc: true
    md_extensions: -ascii_identifiers
---

```{r parse-meta, include=FALSE}
NAMES <- strsplit(rmarkdown::metadata$title, "（|）")[[1]]
NAME_CN <- NAMES[1]
NAME_EN <- NAMES[2]
CODE <- rmarkdown::metadata$code
SDK <- rmarkdown::metadata$sdk
```

# 基本信息

* **显示名称**：`r NAME_CN`
* **英文名称**：`r NAME_EN`
* **题目编号**：`r CODE`
* **任务描述**：测查记忆力，特别是个体的空间短时记忆力
* **测查能力**：记忆力-短时记忆
* **相关任务**：[位置记忆](`r blogdown::shortcode("relref", "00301_spatialSpan.html")`)

# 前端交互

以**Peak**的设计为准。

# 后台配置

## 游戏参数

目前不需要配置参数。

```{r configs, echo=FALSE, message=FALSE}
# knitr::kable(
#   readr::read_csv(
#     here::here("content", "resources", "config", NAME_EN, "configs.csv")
#   ),
#   caption = "配置参数总表"
# )
```

## 数据记录

```{r recording-variables, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("content", "resources", "config", NAME_EN, "recs.csv")
  ),
  caption = "原始数据变量列表"
)
```

## 试题算分

```{r sdk-score, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("content", "resources", "config", NAME_EN, "sdk.csv")
  ),
  caption = paste0("传入参数（算分码：`", SDK, "`）")
)
```
