---
# heading of document
title: 快速归类（Classification） # Chinese name（English name）
author: 张亮
date: 2018-11-06 # format 2006-01-01
# slug
slug: 00603-classification # code-English name
# specific parameters for current task
code: "00603"
sdk: 200
# hugo taxonomy related
tasknames: "选择反应时"
categories:
- 文档
- C2框架
- 幼儿
bibliography: "scoring.bib"
# blogdown output
output:
  blogdown::html_page:
    toc: true
    md_extensions: -ascii_identifiers
---

```{r parse-meta, include=FALSE}
NAMES <- strsplit(rmarkdown::metadata$title, "（|）")[[1]]
NAME_CN <- NAMES[1]
NAME_EN <- NAMES[2]
CODE <- rmarkdown::metadata$code
SDK <- rmarkdown::metadata$sdk
```

# 基本信息

* **显示名称**：`r NAME_CN`
* **英文名称**：`r NAME_EN`
* **题目编号**：`r CODE`
* **任务描述**：
* **测查能力**：
* **相关任务**：

# 前端交互

以梅鹏提供的玩法为准。

# 后台配置

## 游戏参数

目前不设置配置参数。

```{r configs, echo=FALSE, message=FALSE}
# knitr::kable(
#   readr::read_csv(
#     here::here("R", "config", NAME_EN, "configs.csv")
#   ),
#   caption = "配置参数总表"
# )
```

## 数据记录

```{r recording-variables, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("R", "config", NAME_EN, "recs.csv")
  ),
  caption = "原始数据变量列表"
)
```

## 试题算分

```{r sdk-score, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("R", "config", NAME_EN, "sdk.csv")
  ),
  caption = paste0("传入参数（算分码：`", SDK, "`）")
)
```

## 算分方法

采用一个考虑了速度准确性权衡的叫做`RCS`[@woltz_availability_2006; @vandierendonck_comparison_2017]的指标作为原始分。规则：

$$RCS = \frac{PC}{RT_c}$$

其中$PC$表示用户作答的正确比例（未作答记为错误），而$RT_c$则表示用户所有作答正确情况下反应时的平均值。值得注意的是这里$RT_c$采用的**单位**：在以前的版本中是毫秒，但是这会导致$RCS$很小，因此新版本应当修改为以**秒**为单位。同时，$RT_c$的可能范围需定在0.1-3秒之间。

原始分的取值范围为0~100。

# 参考文献
