---
# heading of document
title: 语言划消测验（cancellation） # Chinese name（English name）
author: 张亮
date: 2018-05-31 # format 2006-01-01
# slug
slug: 042XX-cancellation # code-English name
# specific parameters for current task
code: 042XX
sdk: 203
# hugo taxonomy related
tasknames: 划消测验
categories:
  - 文档
  - 修复
# blogdown output
output:
  blogdown::html_page:
    toc: true
    md_extensions: -ascii_identifiers
---

```{r parse-meta, include=FALSE}
NAMES <- strsplit(rmarkdown::metadata$title, "（|）")[[1]]
NAME_CN <- NAMES[1]
NAME_EN <- NAMES[2]
CODE <- rmarkdown::metadata$code
SDK <- rmarkdown::metadata$sdk
```

# 基本信息

* **显示名称**：`r NAME_CN`
* **英文名称**：`r NAME_EN`
* **题目编号**：`r CODE`
* **任务描述**：划消测验包含6个经典语言相关的任务，即**符号判断**（`04201`）、**字形判断**（`04202`）、**声调判断**（`04203`）、**词语判断**（`04204`）、**语义判断**（`04205`）和**拼音判断**（`04206`）。
* **测查能力**：语言/反应力-言语速度
<!-- * **相关任务**： -->

<!-- # 前端交互 -->

<!-- ## 基本逻辑 -->

<!-- ## 详细说明 -->

# 后台配置

<!-- ## 游戏参数 -->

<!-- ```{r configs, echo=FALSE, message=FALSE} -->
<!-- # knitr::kable( -->
<!-- #   readr::read_csv( -->
<!-- #     here::here("data", "config", NAME_EN, "configs.csv") -->
<!-- #   ), -->
<!-- #   caption = "配置参数总表" -->
<!-- # ) -->
<!-- ``` -->

## 数据记录

```{r recording-variables, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("data", "config", NAME_EN, "recs.csv")
  ),
  caption = "原始数据变量列表[^std]"
)
```

[^std]: 请参考[标准](`r blogdown::shortcode("relref", "standard.html")`)。

## 试题算分

```{r sdk-score, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("data", "config", NAME_EN, "sdk.csv")
  ),
  caption = paste0("传入参数（算分码：`", SDK, "`）")
)
```
