---
# heading of document
title: 保卫地球（ProtectEarth） # Chinese name（English name）
author: 张亮
date: 2018-11-06 # format 2006-01-01
# slug
slug: 08501-protectearth # code-English name
# specific parameters for current task
code: "08501"
sdk: 203
# hugo taxonomy related
tasknames: 问题解决
categories:
  - 文档
  - C2框架
  - 幼儿
# blogdown output
output:
  blogdown::html_page:
    toc: true
    md_extensions: -ascii_identifiers
---

```{r parse-meta, include=FALSE}
NAMES <- strsplit(rmarkdown::metadata$title, "（|）")[[1]]
NAME_CN <- NAMES[1]
NAME_EN <- NAMES[2]
CODE <- rmarkdown::metadata$code
SDK <- rmarkdown::metadata$sdk
```

# 基本信息

* **显示名称**：`r NAME_CN`
* **英文名称**：`r NAME_EN`
* **题目编号**：`r CODE`
* **任务描述**：测查思维力，特别是面对复杂问题进行深入思考并作出解答的能力。
* **测查能力**：思维力-思维深刻性
* **相关任务**：暂无

# 前端交互

以**Peak**的玩法为准。

# 后台配置

## 游戏参数

目前不设置配置参数。

```{r configs, echo=FALSE, message=FALSE}
# knitr::kable(
#   readr::read_csv(
#     here::here("content", "resources", "config", NAME_EN, "configs.csv")
#   ),
#   caption = "配置参数总表"
# )
```

## 数据记录

对于每一次陨石对地球的冲击，需记录以下数据：

```{r recording-variables, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("content", "resources", "config", NAME_EN, "recs.csv")
  ),
  caption = "原始数据变量列表"
)
```

## 试题算分

```{r sdk-score, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("content", "resources", "config", NAME_EN, "sdk.csv")
  ),
  caption = paste0("传入参数（算分码：`", SDK, "`）")
)
```
