---
# heading of document
title: 声音波动（AuditoryProcessing） # Chinese name（English name）
author: 刘楚麒
date: 2018-12-29 # format 2006-01-01
# slug
slug: # code-English name
# specific parameters for current task
code: "08801"
sdk: 999
# hugo taxonomy related
tags: 听知觉音调加工
categories: 文档
# blogdown output
output:
  blogdown::html_page:
    toc: true
    md_extensions: -ascii_identifiers
---

```{r parse-meta, include=FALSE}
NAMES <- strsplit(rmarkdown::metadata$title, "（|）")[[1]]
NAME_CN <- NAMES[1]
NAME_EN <- NAMES[2]
CODE <- rmarkdown::metadata$code
SDK <- rmarkdown::metadata$sdk
```

# 基本信息

* **显示名称**：`r NAME_CN`
* **英文名称**：`r NAME_EN`
* **题目编号**：`r CODE`
* **任务描述**：训练听知觉，特别是音调分辨能力。
* **测查能力**：感知觉-听知觉

# 前端交互

## 基本逻辑

任务中会先后呈现两个声音，屏幕上一左一右有两个按钮“升调”和“降调”，用户需要根据听到的声音按顺序点击相应按钮，难度会逐渐提高，表现为呈现的声音刺激持续时间越来越短，记录用户的正确率和反应时。

## 详细说明

### 流程说明

每个试次流程如下：

1. 分别呈现1秒的声音刺激（升调或降调随机）二至四个，声音都播放结束后让用户根据相应顺序点击按钮。
1. 操作反馈。结束每次反应后立即呈现反馈。
1. 试次间间隔。反馈消失后1s开始下一个试次。

### 刺激说明

使用软件制作1秒的声调和降调声音和压缩声音。

# 后台配置

## 数据记录

```{r recording-variables, echo=FALSE, message=FALSE}
knitr::kable(
  readr::read_csv(
    here::here("R", "config", NAME_EN, "recs.csv")
  ),
  caption = "原始数据变量列表"
)
```
